### ISSUE TITLE
[1.12.2-1.3.2] Crash when placing collectors

### ISSUE THREAD

**Issue by EngineersBox** [royal-reject-studios/Auxilium#2]
Hi, I've been using AuxilliumEquivalence 1.12.2-1.3.2 with ProjectE and other mods with FTB Ultimate Reloaded and found a crash when placing any of the condensors. It seems like the initialiser method that it supposed to be available for the condensor tile entity is not (possibly private and not public method?). Attached is the crash log below:

[crash-2021-06-15_13.53.45-client.txt](https://github.com/royal-reject-studios/Auxilium/files/6652701/crash-2021-06-15_13.53.45-client.txt)

**Comment by EngineersBox** [comment]
If i have some time ill try to scope it out myself, though i'm not familiar with your codebase so that might take a bit.

**Comment by RoyalReject** [comment]
1.12.2 Is no longer supported, the crash is from when they changed to use long instead of int, I lost the code for 1.12.2 but projectex is a good replace for that version

**Comment by EngineersBox** [comment]
Alrighty thanks for that. I'll use ProjectEX instead 👍🏽
